### ISSUE TITLE
Can't delete lock icon from Home app list.

### ISSUE THREAD

**Issue by piroshi1112** [aschaper/homebridge-sesame#10]
I am always grateful for your help.
The other day, I tried to run homebridge-sesame on another terminal, deleted the description of config.json and uninstalled the plug-in, but the lock icon does not disappear from the list of Home applications.

Please advise how to remove the lock icon.
Thank you.

**Comment by sleepyarmistice** [comment]
As far as I know, the only way to remove the device is to remove homebridge from your set up and then re-add it.

**Comment by piroshi1112** [comment]
Thank you for your reply.
If you remove Homebridge from your setup and add it again, the lock icon will be restored. Although the description of config.json was deleted and the plug-in was deleted.

The following message was left in the log when starting Homebridge.

```
Mar 12 21:03:35 darwin homebridge[435]: Failed to find plugin to handle accessory Bottom
Mar 12 21:03:35 darwin homebridge[435]: Failed to find plugin to handle accessory Top
```

**Comment by piroshi1112** [comment]
After uninstalling homebridge and installing it again, the lock icon disappeared. Thank you very much.
