### ISSUE TITLE
Encountered an error when trying to get locks: StatusCodeError: 400

### ISSUE THREAD

**Issue by aschzero** [aschaper/homebridge-sesame#2]
Preemptively creating this issue incase others visit this repo to report this error.

This is due to a known issue with the Sesame API and I've reported it here: https://community.candyhouse.co/t/v1-sesames-endpoint-returning-400-bad-request-but-others-still-work/1265/2

Unfortunately there doesn't appear to be any workaround so hopefully this gets fixed very soon.

**Comment by aschzero** [comment]
@sleepyarmistice It looks like the issue has been resolved, can you please confirm it's working for you? You might need to restart homebridge.

**Comment by sleepyarmistice** [comment]
Yep, looks like it’s working. Thanks!

**Comment by aschzero** [comment]
Awesome, thanks for confirming.
