### ISSUE TITLE
Implement V3 API

### ISSUE THREAD

**Issue by luthfielaroeha** [aschaper/homebridge-sesame#3]
Hello, is it hard to implement V3 API ?
https://docs.candyhouse.co/#introduction

**Comment by aschzero** [comment]
Hi @luthfielaroeha, I skimmed through the docs it looks like it should be pretty straightforward to start using v3. I'll start working on this shortly and will keep you posted on any updates. Thanks for bringing this to my attention!

**Comment by aschzero** [comment]
An update has just been published which uses v3 of the Sesame API. Please see the release notes as this version has some breaking changes concerning the homebridge config file: https://github.com/aschzero/homebridge-sesame/releases/tag/v2.0.0

Please let me know if you have any questions or run into any issues.
